version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=app_db
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  nginx-proxy:
    build: ./nginx-proxy
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - frontend
      - backend

networks:
  webnet:
    name: webnet

volumes:
  db_data:
